hyb:
  models:
    lstm_model: best_model.pth
    sif_model: sparse_isolation_forest_model.pkl
lstm:
  BATCH_SIZE: 64
  EPOCHS: 200
  HIDDEN_SIZE: 4
  LR: 0.01
  THRESHOLD_HIGH: 0.4559980034828186
shared:
  TIME_WINDOW: 10
  data:
    test_data: ../dataset/FD/test.csv
    train_data: ../dataset/FD/train.csv
  features:
  - RSSI
  - Link Quality
  - Ping Delay
spa:
  GLOBAL_THRESHOLD: 0.6028045095423143
  GLOBAL_original_THRESHOLD: 0.6028045095423143
  NORMAL_THRESHOLD: 0.4749808761904588
  max_depth: 5
  min_samples_split: 2
  n_trees: 25
  subsample_size: 128
